print("Добро пожаловать в ветеренарную клинику")
print()
print(input("вид питомца?"))
print("питон")
print(input("возраст?"))
print("34 года.")
print(input("кличка?"))
print("Каа.")
print("хорошо.")
input("жаба")